# Generated by Django 4.2.30 on 2026-06-03 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('item_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('serial_number', models.CharField(blank=True, max_length=160)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('manufacturer', models.CharField(blank=True, max_length=160)),
                ('inventory_number', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item_id'],
            },
        ),
        migrations.CreateModel(
            name='AssetQrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_value', models.CharField(max_length=255, unique=True)),
                ('payload_url', models.CharField(max_length=255)),
                ('label_text', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='inventory.assetitem')),
            ],
            options={
                'ordering': ['item_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('inventory_manager', 'Inventory manager')], default='member', max_length=32)),
                ('pin_hash', models.CharField(max_length=256)),
                ('pin_updated_at', models.DateTimeField(blank=True, null=True)),
                ('pin_reset_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='QrPrintBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('printed', 'Printed')], default='draft', max_length=16)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_print_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetCurrentState',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='current_state', serialize=False, to='inventory.assetitem')),
                ('condition', models.CharField(choices=[('working', 'Работает'), ('needs_attention', 'Требует внимания'), ('broken', 'Сломано'), ('unknown', 'Неизвестно')], default='working', max_length=32)),
                ('lifecycle_status', models.CharField(choices=[('active', 'Активно'), ('lost', 'Потеряно'), ('repair', 'Ремонт'), ('retired', 'Выведено'), ('disposed', 'Утилизировано')], default='active', max_length=32)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('checkout_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QrPrintBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_index', models.PositiveIntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.qrprintbatch')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.assetqrcode')),
            ],
            options={
                'ordering': ['position_index', 'id'],
            },
        ),
        migrations.AddField(
            model_name='qrprintbatch',
            name='qr_codes',
            field=models.ManyToManyField(related_name='print_batches', through='inventory.QrPrintBatchItem', to='inventory.assetqrcode'),
        ),
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_type', models.CharField(choices=[('person', 'Person'), ('location', 'Location'), ('external', 'External'), ('retired', 'Retired')], max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('is_self_service_source', models.BooleanField(default=False)),
                ('is_temporary', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holder', to='inventory.person')),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_holders', to='inventory.person')),
            ],
            options={
                'ordering': ['holder_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('AssetRegistered', 'Asset registered'), ('AssetTransferred', 'Asset transferred'), ('AssetAuditRecorded', 'Asset audit recorded'), ('AssetCorrectionRecorded', 'Asset correction recorded'), ('AssetRetired', 'Asset retired'), ('AssetReactivated', 'Asset reactivated'), ('StockReceived', 'Stock received'), ('StockMoved', 'Stock moved'), ('StockIssued', 'Stock issued'), ('StockAuditRecorded', 'Stock audit recorded'), ('StockAuditAdjusted', 'Stock audit adjusted')], max_length=64)),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('correction_of_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='inventory.eventlog')),
                ('recorded_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gearflow_recorded_events', to=settings.AUTH_USER_MODEL)),
                ('recorded_by_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_events', to='inventory.person')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('file', 'File'), ('link', 'Link'), ('qr_scan', 'QR scan')], max_length=32)),
                ('uri_or_value', models.CharField(max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gearflow_evidence', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='inventory.eventlog')),
            ],
        ),
        migrations.AddField(
            model_name='assetitem',
            name='registered_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_assets', to='inventory.eventlog'),
        ),
        migrations.CreateModel(
            name='AssetEventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_before', models.CharField(blank=True, max_length=32)),
                ('condition_after', models.CharField(blank=True, max_length=32)),
                ('lifecycle_status_before', models.CharField(blank=True, max_length=32)),
                ('lifecycle_status_after', models.CharField(blank=True, max_length=32)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_items', to='inventory.eventlog')),
                ('from_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_events_from', to='inventory.holder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_items', to='inventory.assetitem')),
                ('to_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_events_to', to='inventory.holder')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAuditObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_condition', models.CharField(blank=True, max_length=32)),
                ('observed_condition', models.CharField(blank=True, max_length=32)),
                ('result', models.CharField(choices=[('matched', 'Matched'), ('missing', 'Missing'), ('unexpected_holder', 'Unexpected holder'), ('condition_mismatch', 'Condition mismatch')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_audit_observations', to='inventory.eventlog')),
                ('expected_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expected_audit_observations', to='inventory.holder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_observations', to='inventory.assetitem')),
                ('observed_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observed_audit_observations', to='inventory.holder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='qrprintbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'qr_code'), name='unique_qr_in_print_batch'),
        ),
        migrations.AddConstraint(
            model_name='holder',
            constraint=models.UniqueConstraint(condition=models.Q(('holder_type', 'person'), ('is_active', True)), fields=('linked_person',), name='one_active_holder_per_person'),
        ),
        migrations.AddConstraint(
            model_name='assetqrcode',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('item',), name='one_active_qr_per_asset'),
        ),
        migrations.AddIndex(
            model_name='asseteventitem',
            index=models.Index(fields=['item'], name='inventory_a_item_id_9a7176_idx'),
        ),
        migrations.AddConstraint(
            model_name='asseteventitem',
            constraint=models.UniqueConstraint(fields=('event', 'item'), name='unique_asset_item_per_event'),
        ),
        migrations.AddField(
            model_name='assetcurrentstate',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_assets', to='inventory.holder'),
        ),
        migrations.AddField(
            model_name='assetcurrentstate',
            name='last_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_state_updates', to='inventory.eventlog'),
        ),
        migrations.AddConstraint(
            model_name='assetauditobservation',
            constraint=models.UniqueConstraint(fields=('event', 'item'), name='unique_asset_audit_observation'),
        ),
        migrations.AddIndex(
            model_name='assetcurrentstate',
            index=models.Index(fields=['holder'], name='inventory_a_holder__756b53_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcurrentstate',
            index=models.Index(fields=['due_on'], name='inventory_a_due_on_22941f_idx'),
        ),
    ]
