# Generated by Django 4.2.30 on 2026-06-03 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_seed_default_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetauditobservation',
            options={'verbose_name': 'наблюдение аудита', 'verbose_name_plural': 'наблюдения аудита'},
        ),
        migrations.AlterModelOptions(
            name='assetcurrentstate',
            options={'verbose_name': 'текущее состояние', 'verbose_name_plural': 'текущее состояние'},
        ),
        migrations.AlterModelOptions(
            name='asseteventitem',
            options={'verbose_name': 'строка события оборудования', 'verbose_name_plural': 'строки событий оборудования'},
        ),
        migrations.AlterModelOptions(
            name='assetitem',
            options={'ordering': ['item_id'], 'verbose_name': 'оборудование', 'verbose_name_plural': 'оборудование'},
        ),
        migrations.AlterModelOptions(
            name='assetqrcode',
            options={'ordering': ['item_id', '-created_at'], 'verbose_name': 'QR-код', 'verbose_name_plural': 'QR-коды'},
        ),
        migrations.AlterModelOptions(
            name='eventevidence',
            options={'verbose_name': 'доказательство события', 'verbose_name_plural': 'доказательства событий'},
        ),
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ['-recorded_at', '-id'], 'verbose_name': 'событие', 'verbose_name_plural': 'журнал событий'},
        ),
        migrations.AlterModelOptions(
            name='holder',
            options={'ordering': ['holder_type', 'name'], 'verbose_name': 'держатель', 'verbose_name_plural': 'держатели'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['display_name'], 'verbose_name': 'человек', 'verbose_name_plural': 'люди'},
        ),
        migrations.AlterModelOptions(
            name='qrprintbatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'пакет печати QR', 'verbose_name_plural': 'пакеты печати QR'},
        ),
        migrations.AlterModelOptions(
            name='qrprintbatchitem',
            options={'ordering': ['position_index', 'id'], 'verbose_name': 'QR в пакете печати', 'verbose_name_plural': 'QR в пакете печати'},
        ),
        migrations.AlterField(
            model_name='assetauditobservation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_audit_observations', to='inventory.eventlog', verbose_name='событие'),
        ),
        migrations.AlterField(
            model_name='assetauditobservation',
            name='expected_condition',
            field=models.CharField(blank=True, max_length=32, verbose_name='ожидаемое состояние'),
        ),
        migrations.AlterField(
            model_name='assetauditobservation',
            name='expected_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expected_audit_observations', to='inventory.holder', verbose_name='ожидаемый держатель'),
        ),
        migrations.AlterField(
            model_name='assetauditobservation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_observations', to='inventory.assetitem', verbose_name='оборудование'),
        ),
        migrations.AlterField(
            model_name='assetauditobservation',
            name='note',
            field=models.TextField(blank=True, verbose_name='заметка'),
        ),
        migrations.AlterField(
            model_name='assetauditobservation',
            name='observed_condition',
            field=models.CharField(blank=True, max_length=32, verbose_name='фактическое состояние'),
        ),
        migrations.AlterField(
            model_name='assetauditobservation',
            name='observed_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observed_audit_observations', to='inventory.holder', verbose_name='фактический держатель'),
        ),
        migrations.AlterField(
            model_name='assetauditobservation',
            name='result',
            field=models.CharField(choices=[('matched', 'совпадает'), ('missing', 'не найдено'), ('unexpected_holder', 'неожиданный держатель'), ('condition_mismatch', 'расхождение состояния')], max_length=32, verbose_name='результат'),
        ),
        migrations.AlterField(
            model_name='assetcurrentstate',
            name='checkout_reason',
            field=models.TextField(blank=True, verbose_name='причина взятия'),
        ),
        migrations.AlterField(
            model_name='assetcurrentstate',
            name='condition',
            field=models.CharField(choices=[('working', 'Работает'), ('needs_attention', 'Требует внимания'), ('broken', 'Сломано'), ('unknown', 'Неизвестно')], default='working', max_length=32, verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='assetcurrentstate',
            name='due_on',
            field=models.DateField(blank=True, null=True, verbose_name='вернуть до'),
        ),
        migrations.AlterField(
            model_name='assetcurrentstate',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_assets', to='inventory.holder', verbose_name='текущий держатель'),
        ),
        migrations.AlterField(
            model_name='assetcurrentstate',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='current_state', serialize=False, to='inventory.assetitem', verbose_name='оборудование'),
        ),
        migrations.AlterField(
            model_name='assetcurrentstate',
            name='last_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_state_updates', to='inventory.eventlog', verbose_name='последнее событие'),
        ),
        migrations.AlterField(
            model_name='assetcurrentstate',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Активно'), ('lost', 'Потеряно'), ('repair', 'Ремонт'), ('retired', 'Выведено'), ('disposed', 'Утилизировано')], default='active', max_length=32, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='assetcurrentstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='asseteventitem',
            name='condition_after',
            field=models.CharField(blank=True, max_length=32, verbose_name='состояние после'),
        ),
        migrations.AlterField(
            model_name='asseteventitem',
            name='condition_before',
            field=models.CharField(blank=True, max_length=32, verbose_name='состояние до'),
        ),
        migrations.AlterField(
            model_name='asseteventitem',
            name='due_on',
            field=models.DateField(blank=True, null=True, verbose_name='вернуть до'),
        ),
        migrations.AlterField(
            model_name='asseteventitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_items', to='inventory.eventlog', verbose_name='событие'),
        ),
        migrations.AlterField(
            model_name='asseteventitem',
            name='from_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_events_from', to='inventory.holder', verbose_name='откуда'),
        ),
        migrations.AlterField(
            model_name='asseteventitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_items', to='inventory.assetitem', verbose_name='оборудование'),
        ),
        migrations.AlterField(
            model_name='asseteventitem',
            name='lifecycle_status_after',
            field=models.CharField(blank=True, max_length=32, verbose_name='статус после'),
        ),
        migrations.AlterField(
            model_name='asseteventitem',
            name='lifecycle_status_before',
            field=models.CharField(blank=True, max_length=32, verbose_name='статус до'),
        ),
        migrations.AlterField(
            model_name='asseteventitem',
            name='note',
            field=models.TextField(blank=True, verbose_name='заметка'),
        ),
        migrations.AlterField(
            model_name='asseteventitem',
            name='to_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_events_to', to='inventory.holder', verbose_name='куда'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='asset_type',
            field=models.CharField(max_length=80, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='создал'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=160, verbose_name='инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='item_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=160, verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='model',
            field=models.CharField(blank=True, max_length=160, verbose_name='модель'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='name',
            field=models.CharField(max_length=160, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='registered_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_assets', to='inventory.eventlog', verbose_name='событие регистрации'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=160, verbose_name='серийный номер'),
        ),
        migrations.AlterField(
            model_name='assetqrcode',
            name='code_value',
            field=models.CharField(max_length=255, unique=True, verbose_name='значение QR'),
        ),
        migrations.AlterField(
            model_name='assetqrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='assetqrcode',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='inventory.assetitem', verbose_name='оборудование'),
        ),
        migrations.AlterField(
            model_name='assetqrcode',
            name='label_text',
            field=models.CharField(max_length=80, verbose_name='надпись'),
        ),
        migrations.AlterField(
            model_name='assetqrcode',
            name='payload_url',
            field=models.CharField(max_length=255, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='assetqrcode',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='отозван'),
        ),
        migrations.AlterField(
            model_name='assetqrcode',
            name='status',
            field=models.CharField(choices=[('active', 'активен'), ('revoked', 'отозван')], default='active', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='eventevidence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='eventevidence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gearflow_evidence', to=settings.AUTH_USER_MODEL, verbose_name='создал'),
        ),
        migrations.AlterField(
            model_name='eventevidence',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='inventory.eventlog', verbose_name='событие'),
        ),
        migrations.AlterField(
            model_name='eventevidence',
            name='evidence_type',
            field=models.CharField(choices=[('photo', 'фото'), ('file', 'файл'), ('link', 'ссылка'), ('qr_scan', 'QR-скан')], max_length=32, verbose_name='тип доказательства'),
        ),
        migrations.AlterField(
            model_name='eventevidence',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='eventevidence',
            name='uri_or_value',
            field=models.CharField(max_length=512, verbose_name='файл или значение'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='correction_of_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='inventory.eventlog', verbose_name='исправляет событие'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('AssetRegistered', 'Оборудование зарегистрировано'), ('AssetTransferred', 'Оборудование передано'), ('AssetAuditRecorded', 'Проведен аудит оборудования'), ('AssetCorrectionRecorded', 'Записана коррекция оборудования'), ('AssetRetired', 'Оборудование выведено'), ('AssetReactivated', 'Оборудование возвращено в оборот'), ('StockReceived', 'Мерч поступил'), ('StockMoved', 'Мерч перемещен'), ('StockIssued', 'Мерч выдан'), ('StockAuditRecorded', 'Проведен аудит мерча'), ('StockAuditAdjusted', 'Скорректирован остаток мерча')], max_length=64, verbose_name='тип события'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='happened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='произошло'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='данные'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='reason',
            field=models.TextField(blank=True, verbose_name='причина'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='записано'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='recorded_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gearflow_recorded_events', to=settings.AUTH_USER_MODEL, verbose_name='записал администратор'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='recorded_by_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_events', to='inventory.person', verbose_name='записал участник'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='окончание'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='holder_type',
            field=models.CharField(choices=[('person', 'человек'), ('location', 'место'), ('external', 'внешний держатель'), ('retired', 'выведено из оборота')], max_length=32, verbose_name='тип держателя'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='is_self_service_source',
            field=models.BooleanField(default=False, verbose_name='самовыдача по QR'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='is_temporary',
            field=models.BooleanField(default=False, verbose_name='временный'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='linked_person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holder', to='inventory.person', verbose_name='связанный человек'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_holders', to='inventory.person', verbose_name='ответственный'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='name',
            field=models.CharField(max_length=160, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='начало'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлен'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='person',
            name='display_name',
            field=models.CharField(max_length=160, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pin_hash',
            field=models.CharField(max_length=256, verbose_name='PIN-хеш'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pin_reset_required',
            field=models.BooleanField(default=False, verbose_name='нужно сбросить PIN'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pin_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PIN обновлен'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('member', 'Участник'), ('inventory_manager', 'Ответственный за учет')], default='member', max_length=32, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлен'),
        ),
        migrations.AlterField(
            model_name='qrprintbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='qrprintbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_print_batches', to=settings.AUTH_USER_MODEL, verbose_name='создал'),
        ),
        migrations.AlterField(
            model_name='qrprintbatch',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='напечатан'),
        ),
        migrations.AlterField(
            model_name='qrprintbatch',
            name='qr_codes',
            field=models.ManyToManyField(related_name='print_batches', through='inventory.QrPrintBatchItem', to='inventory.assetqrcode', verbose_name='QR-коды'),
        ),
        migrations.AlterField(
            model_name='qrprintbatch',
            name='status',
            field=models.CharField(choices=[('draft', 'черновик'), ('printed', 'напечатан')], default='draft', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='qrprintbatch',
            name='title',
            field=models.CharField(blank=True, max_length=160, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='qrprintbatchitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.qrprintbatch', verbose_name='пакет печати'),
        ),
        migrations.AlterField(
            model_name='qrprintbatchitem',
            name='position_index',
            field=models.PositiveIntegerField(default=0, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='qrprintbatchitem',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.assetqrcode', verbose_name='QR-код'),
        ),
    ]
