# Generated by Django 4.2.30 on 2026-06-03 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_alter_assetauditobservation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetKit',
            fields=[
                ('kit_id', models.CharField(blank=True, max_length=32, primary_key=True, serialize=False, verbose_name='ID комплекта')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('status', models.CharField(choices=[('active', 'активен'), ('archived', 'в архиве')], default='active', max_length=16, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_kits', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name': 'комплект',
                'verbose_name_plural': 'комплекты',
                'ordering': ['kit_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='holder',
            options={'ordering': ['holder_type', 'name'], 'verbose_name': 'место или ответственный', 'verbose_name_plural': 'места и ответственные'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['display_name'], 'verbose_name': 'участник', 'verbose_name_plural': 'участники'},
        ),
        migrations.AlterField(
            model_name='holder',
            name='holder_type',
            field=models.CharField(choices=[('person', 'участник'), ('location', 'место хранения'), ('external', 'внешний держатель'), ('retired', 'списано')], max_length=32, verbose_name='тип держателя'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='is_self_service_source',
            field=models.BooleanField(default=False, help_text='Если включено, оборудование из этого места можно взять самому через QR-страницу.', verbose_name='можно брать по QR'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('member', 'Участник'), ('inventory_manager', 'Ответственный за учет')], default='member', help_text='Роль участника для QR-сценариев. Вход в админку управляется отдельно в разделе пользователей Django.', max_length=32, verbose_name='роль'),
        ),
        migrations.CreateModel(
            name='StockSku',
            fields=[
                ('sku_id', models.CharField(blank=True, max_length=32, primary_key=True, serialize=False, verbose_name='SKU')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='категория')),
                ('unit', models.CharField(default='шт', max_length=24, verbose_name='единица')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_skus', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name': 'мерч',
                'verbose_name_plural': 'мерч',
                'ordering': ['sku_id'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.holder', verbose_name='место или ответственный')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='inventory.stocksku', verbose_name='мерч')),
            ],
            options={
                'verbose_name': 'остаток мерча',
                'verbose_name_plural': 'остатки мерча',
                'ordering': ['sku_id', 'holder__name'],
            },
        ),
        migrations.CreateModel(
            name='AssetKitQrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_value', models.CharField(max_length=255, unique=True, verbose_name='значение QR')),
                ('payload_url', models.CharField(max_length=255, verbose_name='ссылка')),
                ('label_text', models.CharField(max_length=80, verbose_name='надпись')),
                ('status', models.CharField(choices=[('active', 'активен'), ('revoked', 'отозван')], default='active', max_length=16, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='отозван')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='inventory.assetkit', verbose_name='комплект')),
            ],
            options={
                'verbose_name': 'QR-код комплекта',
                'verbose_name_plural': 'QR-коды комплектов',
                'ordering': ['kit_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_index', models.PositiveIntegerField(default=0, verbose_name='позиция')),
                ('note', models.CharField(blank=True, max_length=160, verbose_name='заметка')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.assetitem', verbose_name='оборудование')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_items', to='inventory.assetkit', verbose_name='комплект')),
            ],
            options={
                'verbose_name': 'предмет комплекта',
                'verbose_name_plural': 'предметы комплекта',
                'ordering': ['position_index', 'id'],
            },
        ),
        migrations.AddField(
            model_name='assetkit',
            name='items',
            field=models.ManyToManyField(related_name='kits', through='inventory.AssetKitItem', to='inventory.assetitem', verbose_name='оборудование'),
        ),
        migrations.CreateModel(
            name='StockEventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('note', models.TextField(blank=True, verbose_name='заметка')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.eventlog', verbose_name='событие')),
                ('from_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_events_from', to='inventory.holder', verbose_name='откуда')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_items', to='inventory.stocksku', verbose_name='мерч')),
                ('to_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_events_to', to='inventory.holder', verbose_name='куда')),
            ],
            options={
                'verbose_name': 'строка события мерча',
                'verbose_name_plural': 'строки событий мерча',
                'indexes': [models.Index(fields=['sku'], name='inventory_s_sku_id_09f741_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('sku', 'holder'), name='unique_stock_balance_per_holder'),
        ),
        migrations.AddConstraint(
            model_name='assetkitqrcode',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('kit',), name='one_active_qr_per_kit'),
        ),
        migrations.AddConstraint(
            model_name='assetkititem',
            constraint=models.UniqueConstraint(fields=('kit', 'item'), name='unique_asset_in_kit'),
        ),
    ]
