# Generated by Django 4.2.30 on 2026-06-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_assetkit_alter_holder_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverdueAssetCurrentState',
            fields=[
            ],
            options={
                'verbose_name': 'просрочка',
                'verbose_name_plural': 'просрочки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.assetcurrentstate',),
        ),
        migrations.AlterField(
            model_name='stocksku',
            name='sku_id',
            field=models.CharField(blank=True, help_text='Можно оставить пустым: система выдаст код вроде SKU-001.', max_length=32, primary_key=True, serialize=False, verbose_name='артикул / SKU'),
        ),
    ]
